### ISSUE TITLE
investigation: db table per request type

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#303]
Due to expected high number of requests in zenodo-rdm we need to investigate how much effort we require to create one db table per request type

**Comment by ppanero** [comment]
# DB table per requests type

The [RequestMetadata](https://github.com/inveniosoftware/invenio-requests/blob/master/invenio_requests/records/models.py#L22) model class has three columns: id, number and expires at. None of seem to be suitable for partitioning, maybe the `number` since it is an incremental (however, it will grow and we might end up with a high number of partitions).

## Usage

There is no inheritance to other models, but there are two tables with FKs:

- Communities, the FK is defined in the [Mixin](https://github.com/inveniosoftware/invenio-communities/blob/4bf215285d7afa9ecca25fa290c21ac6eb9fa61b/invenio_communities/records/records/models.py#L56) and then passed to the [parent commmunity model class](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/models.py#L32)
- Similarly, it happens with the [BaseMembers](https://github.com/inveniosoftware/invenio-communities/blob/9d71348ed70c7ba55c3521ab2c9c7dbefdf08a7a/invenio_communities/members/records/models.py#L76) and its usage in the [members model class](https://github.com/inveniosoftware/invenio-communities/blob/9d71348ed70c7ba55c3521ab2c9c7dbefdf08a7a/invenio_communities/members/records/models.py#L109)

## Work TODO

1. Make the `__tablename__` configurable via class inheritance, the base `RequestMetadata` should be made abstract/mixin (i.e. no `__tablename__`) to force name declaration.
2. Per module/usage, a new class should be defined:
    - One for the `RDMParentCommunity`
    - One for the `MemberModel`

**Modules involved**: invenio-requests, invenio-communities
**Estimation**: 2pd

## Data migration

Identifying to which table the entries should be moved can be done with a JOIN by FK. Since we can potentially use the old model or mock it, this can be done in-place by the alembic recipe

**Estimation**: 1.5pd

## Extra

The DB table division is meant to lower the load on one DB that has high usage. While splitting in two tables will help diminish the load, it might not be enough.
- The FK is on the `id`, since it is a PK there is an index, which will help with the high selectivity.
- Should we add more context to the request (e.g. req_type). This could be a way to sub-divide the tables by partitioning. This would help only if the partitioning is somehow balanced.

**Comment by ntarocco** [comment]
With @ppanero  conclusions and also taking into account the discussion with @lnielsen, the idea is that in the future we will create a task to hard delete old/expired requests. This should mitigate the potential performance or db integrity issues.
Do we close this issue? Do we want to refer to this nice investigation done by @ppanero somewhere?

**Comment by ppanero** [comment]
It would be nice to persist it yes. It is not an RFC, but a decission. Could it go to the decission log @kpsherva @zzacharo?

@ntarocco one minor question, the requests might have conversations that might have value to the users, although the use cases are slight corner case:

> Community inclusion request, where the curator asks to change the title. The creator changes it, and once accepted it changes it back. If we delete the request there is no track of "I told you to change it".

On the other hand, this is something that should be fix by audit logging, not requests.

**Comment by ntarocco** [comment]
Yes indeed, in the future we should have an audit log with all the changes and record diff, probably. In any case, closed requests will be deleted after quite some time, not very soon.
